### ISSUE TITLE
Retrofit multipart form support

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/client#2]
Hey @tejainece what the plan for this, of course I want to try the lib and first call I need to implement (login) is in form data lol 
Can you tell me the steps and I'll do a PR for this :) 

Do we go for a `@AsFormData` annotation ?

**Comment by Kleak** [comment]
I think it should into the `@GetReq` and friend annotation

**Comment by jaumard** [comment]
Hum strange as it's a post request not a get, that's why I was proposing AsMultipart like the AsJson already present

**Comment by Kleak** [comment]
That's right since it's a parameters it must be the same as `@AsJson`  :)

**Comment by jaumard** [comment]
Ok :) I'll dig into this then see if I'm able to make a PR thx

**Comment by jaumard** [comment]
It might need changes to jaguar_serializer too, as for multipart we need Map<String, String> not Map<String, dynamic>, so jaguar_serializer should be able to serialize for multipart. 
How does it sound ?

**Comment by tejainece** [comment]
@jaumard `@AsForm`, `@AsFormField`, `@AsMultipart`, `@AsMultipartField` should be good.

`jaguar_serializer` can handle `Map<String, String>`.

**Comment by jaumard** [comment]
@Kleak @tejainece the problem here is for example: 
```
class User {
   int age;
  String name;
}
```
This will not cast to `Map<String, String>` but under a multipart data it will need to be. I was thinking to generate a `toMapString` that will transform all fields to `String` automatically

**Comment by jaumard** [comment]
For now I have `type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'`

**Comment by tejainece** [comment]
@jaumard I have added url-encoded-form support https://github.com/Jaguar-dart/client/commit/c3ba261c10fd45b7e327b3cebe9308b9e8976546

But I have not fixed multipart form yet.
