### ISSUE TITLE
Not able to compile android release build

### ISSUE THREAD

**Issue by noisytempo** [Jaguar-dart/client#29]
>flutter build apk --release
Running "flutter packages get" in rozana_customer_app...     0.7s
Initializing gradle...                                       1.1s
Resolving dependencies...                                    3.1s
Gradle task 'assembleRelease'...                                 

Compiler message:
Flutter/.pub-cache/hosted/pub.dartlang.org/jaguar_resty-2.8.8/lib/src/expect.dart:13:28: Error: Type argument '#lib1::Mismatch::M' violates the corresponding type variable bound of 'CustomMismatchMessage'.
Try changing type arguments so that they conform to the bounds.
  CustomMismatchMessage<M> customMessage;
                           ^
Flutter/.pub-cache/hosted/pub.dartlang.org/jaguar_resty-2.8.8/lib/src/expect.dart:8:38: Context: Bound of this variable is violated.
typedef String CustomMismatchMessage<M extends Mismatch>(M mismatch);
                                     ^
Compiler terminated unexpectedly.
 
Gradle task 'assembleRelease'... Done                        8.4s
Gradle task assembleRelease failed with exit code 1

**Comment by tejainece** [comment]
I have published `2.8.9` that is supposed to fix this issue. Can you please test it?

**Comment by noisytempo** [comment]
Yes, it is fixed now. Thanks 🙂
