### ISSUE TITLE
Retrofit status code 2xx

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/client#32]
Currently retrofit take all status as error except 200, it should take between 200 < 300 as a good response.
root cause is resty : https://github.com/Jaguar-dart/client/blob/master/resty/lib/src/jaguar_resty_base.dart#L387

**Comment by tejainece** [comment]
Hi,

I purposefully changed it in this commit: https://github.com/Jaguar-dart/client/commit/335fcd193cfb66e5a5b0fbaae686e33666a000b9

Do you want it changed back?

**Comment by jaumard** [comment]
Hi :) 

Yes for me it was correct previously as say in the doc  `2xx: These codes indicate success. The body section if present is the object returned by the request. It is a MIME format object. It is in MIME format, and may only be in text/plain, text/html or one fo the formats specified as acceptable in the request.`

**Comment by jaumard** [comment]
@tejainece let me know when you revert and deploy this please :) 
Thanks

**Comment by jaumard** [comment]
fixed
