### ISSUE TITLE
Resty: go doesn't handle http status 

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/client#35]
As resty doesn't handle http status, retrofit doesn't handle them either when resty.go is used. 
This is bad as you have different behavior depending on how retrofit generate his http calls. 

@tejainece we can either do the check inside `go`, or create a new method `send` that will do the check one `one` or `list` and use this new method in retrofit instead of `go`

**Comment by jaumard** [comment]
@tejainece can this be fixed and deployed please (on the non proto refactoring version) ? It prevent me to go in production as my retrofit swallow all http errors :( and has it's auto generated I can't path anything myself

**Comment by tejainece** [comment]
Fixed it in https://github.com/Jaguar-dart/client/commit/e915f0e53183acc0e4412af01dfa01c5a824a66e
