### ISSUE TITLE
how to set proxy?

### ISSUE THREAD

**Issue by LuodiJackShen** [Jaguar-dart/client#50]
I am using "Jaguar-dart"  for flutter, fiddler can not capture the net from flutter, so i want to set a proxy like Okhttp, but i did not find the api.

**Comment by wei3** [comment]
> I am using "Jaguar-dart" for flutter, fiddler can not capture the net from flutter, so i want to set a proxy like Okhttp, but i did not find the api.
你解决代理的问题了吗？
