### ISSUE TITLE
Need interceptor and how to get string response.

### ISSUE THREAD

**Issue by RaghuManickam** [Jaguar-dart/client#55]
Hi ,

I am in need of viewing the posted json and response json . So I need a interceptor to do this . Please help me to do this . 

And how to get a string response . I used stringresponse as a return variable I got it for normal string. But to get HTML string response . I am getting exception . Please help me to fix this .

This is a very good library . Please update this library more such as interceptor , Request time out and more like Retrofit . 

Thanks in advance

**Comment by tejainece** [comment]
Use `body` get body of the response: https://pub.dev/documentation/jaguar_resty/2.8.9/jaguar_resty/StringResponse/body.html

**Comment by tejainece** [comment]
Yes, you can write an interceptor to print out request and response body.

**Comment by RaghuManickam** [comment]
String Response I am getting output Thanks for the support . but any code snippets for interceptors ?
